/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "python-office",
  "tagline": "一行代码搞定自动化办公 · Python 自动化办公一站式库",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser",
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    }
  },
  "url": "https://www.python-office.com",
  "baseUrl": "/",
  "organizationName": "CoderWanFeng",
  "projectName": "python-office",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "editUrl": "https://github.com/CoderWanFeng/python-office/tree/main/website/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.png",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "🐍 python-office",
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "mainSidebar",
          "position": "left",
          "label": "📖 文档"
        },
        {
          "to": "/start/overview",
          "label": "🚀 入门",
          "position": "left"
        },
        {
          "to": "/modules/overview",
          "label": "📦 模块",
          "position": "left"
        },
        {
          "to": "/tutorials/overview",
          "label": "🎓 教程",
          "position": "left"
        },
        {
          "href": "https://github.com/CoderWanFeng/python-office",
          "label": "⭐ GitHub",
          "position": "right"
        },
        {
          "href": "https://pypi.org/project/python-office/",
          "label": "📦 PyPI",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "🚀 入门",
          "items": [
            {
              "label": "项目概览",
              "to": "/start/overview"
            },
            {
              "label": "安装",
              "to": "/start/install"
            },
            {
              "label": "5分钟体验",
              "to": "/start/quickstart"
            },
            {
              "label": "常见问题",
              "to": "/start/faq"
            }
          ]
        },
        {
          "title": "📦 模块",
          "items": [
            {
              "label": "模块总览",
              "to": "/modules/overview"
            },
            {
              "label": "Excel",
              "to": "/modules/excel/guide"
            },
            {
              "label": "PDF",
              "to": "/modules/pdf/guide"
            },
            {
              "label": "Image",
              "to": "/modules/image/guide"
            },
            {
              "label": "WeChat",
              "to": "/modules/wechat/guide"
            }
          ]
        },
        {
          "title": "🎓 教程",
          "items": [
            {
              "label": "Excel 30讲",
              "to": "/tutorials/excel-30"
            },
            {
              "label": "PDF 10讲",
              "to": "/tutorials/pdf-10"
            },
            {
              "label": "微信机器人 10讲",
              "to": "/tutorials/wechat-10"
            },
            {
              "label": "OCR 7讲",
              "to": "/tutorials/ocr-7"
            }
          ]
        },
        {
          "title": "🔗 资源",
          "items": [
            {
              "label": "GitHub 仓库",
              "href": "https://github.com/CoderWanFeng/python-office"
            },
            {
              "label": "PyPI 包",
              "href": "https://pypi.org/project/python-office/"
            },
            {
              "label": "微信公众号",
              "href": "https://mp.weixin.qq.com/s/Z3WhrmYeavrCw_FOXgiDPA"
            },
            {
              "label": "关于项目",
              "to": "/about/overview"
            },
            {
              "label": "更新日志",
              "to": "/about/changelog"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 python-office · 程序员晚枫. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "json",
        "yaml",
        "diff"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
